"""initial

Revision ID: 0f070585f6e2
Revises: 60ef3e912325
Create Date: 2025-11-12 19:25:50.512506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f070585f6e2'
down_revision: Union[str, Sequence[str], None] = '60ef3e912325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_accounts', sa.Column('phone_code_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('default_api_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('default_api_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('default_device_model', sa.String(), nullable=True))
    op.add_column('users', sa.Column('default_system_version', sa.String(), nullable=True))
    op.add_column('users', sa.Column('default_app_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_app_version')
    op.drop_column('users', 'default_system_version')
    op.drop_column('users', 'default_device_model')
    op.drop_column('users', 'default_api_hash')
    op.drop_column('users', 'default_api_id')
    op.drop_column('telegram_accounts', 'phone_code_hash')
    # ### end Alembic commands ###
