"""add failure_threshold

Revision ID: e2ddafb90c4e
Revises: fee6d4b675ca
Create Date: 2025-11-04 20:56:42.926276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ddafb90c4e'
down_revision: Union[str, Sequence[str], None] = 'fee6d4b675ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('failure_threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websites', 'failure_threshold')
    # ### end Alembic commands ###
