"""initial

Revision ID: da95c8b5cc87
Revises: 0f070585f6e2
Create Date: 2025-11-13 21:25:27.547777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da95c8b5cc87'
down_revision: Union[str, Sequence[str], None] = '0f070585f6e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_forward_to_chat_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_forward_to_chat_id')
    # ### end Alembic commands ###
