"""add TG id default

Revision ID: 32089671c7f0
Revises: e2ddafb90c4e
Create Date: 2025-11-05 19:36:44.263279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32089671c7f0'
down_revision: Union[str, Sequence[str], None] = 'e2ddafb90c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_telegram_chat_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_telegram_chat_id')
    # ### end Alembic commands ###
