"""initial

Revision ID: 7db66d7c4718
Revises: da95c8b5cc87
Create Date: 2025-11-15 19:20:45.781847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db66d7c4718'
down_revision: Union[str, Sequence[str], None] = 'da95c8b5cc87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('whitelist_keywords', sa.Text(), nullable=True),
    sa.Column('blacklist_keywords', sa.Text(), nullable=True),
    sa.Column('monitored_channels', sa.Text(), nullable=False),
    sa.Column('forward_to_chat_id', sa.String(), nullable=False),
    sa.Column('replacements', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['telegram_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_tasks_id'), 'monitoring_tasks', ['id'], unique=False)
    op.drop_column('telegram_accounts', 'whitelist_keywords')
    op.drop_column('telegram_accounts', 'monitored_channels')
    op.drop_column('telegram_accounts', 'forward_to_chat_id')
    op.drop_column('telegram_accounts', 'replacements')
    op.drop_column('telegram_accounts', 'blacklist_keywords')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_accounts', sa.Column('blacklist_keywords', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('telegram_accounts', sa.Column('replacements', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('telegram_accounts', sa.Column('forward_to_chat_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('telegram_accounts', sa.Column('monitored_channels', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('telegram_accounts', sa.Column('whitelist_keywords', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_monitoring_tasks_id'), table_name='monitoring_tasks')
    op.drop_table('monitoring_tasks')
    # ### end Alembic commands ###
