"""initial

Revision ID: b837a992b4ec
Revises: 7db66d7c4718
Create Date: 2025-11-16 10:13:58.465537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b837a992b4ec'
down_revision: Union[str, Sequence[str], None] = '7db66d7c4718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_accounts', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_accounts', 'name')
    # ### end Alembic commands ###
